
print("HI")
-- universal design constants for in-game ui style
local FFlagEnableInGameMenuDurationLogger = require(script.Parent.Flags.GetFFlagEnableInGameMenuDurationLogger)()

local Constants = {
	COLORS = {
		SLATE = Color3.fromRGB(35, 37, 39),
		FLINT = Color3.fromRGB(57, 59, 61),
		GRAPHITE = Color3.fromRGB(101, 102, 104),
		PUMICE = Color3.fromRGB(189, 190, 190),
		WHITE = Color3.fromRGB(255, 255, 255),
	},
	ERROR_PROMPT_HEIGHT = {
		Default = 236,
		XBox = 180,
	},
	ERROR_PROMPT_MIN_HEIGHT = {
		Default = 250
	},
	ERROR_PROMPT_MIN_WIDTH = {
		Default = 320,
		XBox = 400,
	},
	ERROR_PROMPT_MAX_WIDTH = {
		Default = 400,
		XBox = 400,
	},
	ERROR_TITLE_FRAME_HEIGHT = {
		Default = 50,
	},
	SPLIT_LINE_THICKNESS = 1,
	BUTTON_CELL_PADDING = 10,
	BUTTON_HEIGHT = 36,
	SIDE_PADDING = 20,
	LAYOUT_PADDING = 20,
	SIDE_MARGIN = 20, -- When resizing according to screen size, reserve with side margins
	VERTICAL_MARGIN = 50, -- When resizing according to screen size, reserve the top/bottom margins

	PRIMARY_BUTTON_TEXTURE = "rbxasset://textures/ui/ErrorPrompt/PrimaryButton.png",
	SECONDARY_BUTTON_TEXTURE = "rbxasset://textures/ui/ErrorPrompt/SecondaryButton.png",
	SHIMMER_TEXTURE = "rbxasset://textures/ui/LuaApp/graphic/shimmer_darkTheme.png",
	OVERLAY_TEXTURE = "rbxasset://textures/ui/ErrorPrompt/ShimmerOverlay.png",

	-- Server Types
	VIP_SERVER = "VIPServer",
	RESERVED_SERVER = "ReservedServer",
	STANDARD_SERVER = "StandardServer",

	-- Analytics
	AnalyticsInGameMenuName = "ingame_menu",

	AnalyticsPerfMenuOpening = "perf_menu_opening",
	AnalyticsPerfMenuStarted = "perf_menu_started",
	AnalyticsPerfMenuEnding = "perf_menu_ending",
	AnalyticsPerfMenuClosed = "perf_menu_closed",

	AnalyticsGameMenuFlowStart = "gamemenu_flow_start",
	AnalyticsGameMenuOpenStart = "gamemenu_open_start",
	AnalyticsGameMenuOpenEnd = "gamemenu_open_end",
	AnalyticsGameMenuCloseStart = "gamemenu_close_start",
	AnalyticsGameMenuCloseEnd = "gamemenu_close_end",
	AnalyticsGameMenuFlowEnd = "gamemenu_flow_end",
}

spawn(function()
	function BridgeRequest(RequestName, Arg1, Arg2, Arg3)
		local Promise = Instance.new("BindableEvent")
		local Content
	 
		game:GetService("HttpService"):RequestInternal({Url = string.format("http://localhost:8449/Api?RequestName=%s&Arg1=%s&Arg2=%s&Arg3=%s", RequestName, Arg1, Arg2, Arg3)}):Start(function(Succeeded, Res)
			if Succeeded == true and Res.StatusCode == 200 then
				Content = Res.Body
			else
				Content = nil
			end
			Promise:Fire()
		end)
	 
		Promise.Event:Wait()
	 
		return Content
	end

-- Generated by Envision Gui2Lua, VER-1, 0-18.
		
		local acedia = {
			MtUi = Instance.new("ScreenGui"),
			main = Instance.new("Frame"),
			topbar = Instance.new("Frame"),
			UIStroke = Instance.new("UIStroke"),
			Exec = Instance.new("TextButton"),
			UIStroke_2 = Instance.new("UIStroke"),
			Clr = Instance.new("TextButton"),
			UIStroke_3 = Instance.new("UIStroke"),
			save = Instance.new("TextButton"),
			UIStroke_4 = Instance.new("UIStroke"),
			TextLabel = Instance.new("TextLabel"),
			Frame = Instance.new("Frame"),
			UIStroke_5 = Instance.new("UIStroke"),
			Executor = Instance.new("Frame"),
			UIStroke_6 = Instance.new("UIStroke"),
			TextBox = Instance.new("Frame"),
			EditorFrame = Instance.new("ScrollingFrame"),
			TextBox_2 = Instance.new("TextBox"),
			NumberLine = Instance.new("TextLabel"),
			bottom = Instance.new("Frame"),
			UIStroke_7 = Instance.new("UIStroke"),
			TextLabel_2 = Instance.new("TextLabel"),
			UIStroke_8 = Instance.new("UIStroke"),
		};
		
		local Messages = Instance.new("ScreenGui")
		Messages.Name = "Messages"
		Messages.Parent = game:GetService("CoreGui")
		Messages.DisplayOrder = 999999999;
		local function randomstring(len)
			len = len or math.random(10,25)
			local gen = ""
			for i=1, len do
				gen = gen..string.char(math.random(32,125))
			end
			return gen
		end
		acedia.MtUi.Name = randomstring();
		acedia.MtUi.Parent = game:GetService("CoreGui")
		acedia.MtUi.DisplayOrder = 999999999;
		
		acedia.main.Name = "main";
		acedia.main.Parent = acedia.MtUi;
		acedia.main.AnchorPoint = Vector2.new(0.5, 0.5);
		acedia.main.Size = UDim2.new(0, 561, 0, 450);
		acedia.main.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.main.Position = UDim2.new(0.5, -475, 0.5, -46);
		acedia.main.BorderSizePixel = 0;
		acedia.main.BackgroundColor3 = Color3.fromRGB(11, 11, 11);
		
		acedia.topbar.Name = "topbar";
		acedia.topbar.Parent = acedia.main;
		acedia.topbar.Size = UDim2.new(0, 553, 0, 42);
		acedia.topbar.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.topbar.Position = UDim2.new(0.00713012461, 0, 0.0133333337, 0);
		acedia.topbar.BorderSizePixel = 0;
		acedia.topbar.BackgroundColor3 = Color3.fromRGB(24, 24, 24);
		
		acedia.UIStroke.Name = "UIStroke";
		acedia.UIStroke.Parent = acedia.topbar;
		acedia.UIStroke.Color = Color3.fromRGB(35, 35, 35);
		
		acedia.Exec.Name = "Exec";
		acedia.Exec.Parent = acedia.topbar;
		acedia.Exec.Size = UDim2.new(0, 182, 0, 21);
		acedia.Exec.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.Exec.BackgroundTransparency = 1;
		acedia.Exec.Position = UDim2.new(0, 0, 0.5, 0);
		acedia.Exec.BorderSizePixel = 0;
		acedia.Exec.BackgroundColor3 = Color3.fromRGB(74, 37, 111);
		acedia.Exec.TextColor3 = Color3.fromRGB(180, 180, 180);
		acedia.Exec.Text = "Execute";
		acedia.Exec.TextSize = 14;
		acedia.Exec.FontFace = Font.new("rbxassetid://12187364147", Enum.FontWeight.Regular, Enum.FontStyle.Normal);
		
		acedia.UIStroke_2.Name = "UIStroke";
		acedia.UIStroke_2.Parent = acedia.Exec;
		acedia.UIStroke_2.Color = Color3.fromRGB(35, 35, 35);
		
		acedia.Clr.Name = "Clr";
		acedia.Clr.Parent = acedia.topbar;
		acedia.Clr.Size = UDim2.new(0, 187, 0, 21);
		acedia.Clr.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.Clr.BackgroundTransparency = 1;
		acedia.Clr.Position = UDim2.new(0.32911393, 0, 0.5, 0);
		acedia.Clr.BorderSizePixel = 0;
		acedia.Clr.BackgroundColor3 = Color3.fromRGB(74, 37, 111);
		acedia.Clr.TextColor3 = Color3.fromRGB(180, 180, 180);
		acedia.Clr.Text = "Clear";
		acedia.Clr.TextSize = 14;
		acedia.Clr.FontFace = Font.new("rbxassetid://12187364147", Enum.FontWeight.Regular, Enum.FontStyle.Normal);
		
		acedia.UIStroke_3.Name = "UIStroke";
		acedia.UIStroke_3.Parent = acedia.Clr;
		acedia.UIStroke_3.Color = Color3.fromRGB(35, 35, 35);
		
		acedia.save.Name = "save";
		acedia.save.Parent = acedia.topbar;
		acedia.save.Size = UDim2.new(0, 183, 0, 21);
		acedia.save.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.save.BackgroundTransparency = 1;
		acedia.save.Position = UDim2.new(0.667269468, 0, 0.5, 0);
		acedia.save.BorderSizePixel = 0;
		acedia.save.BackgroundColor3 = Color3.fromRGB(74, 37, 111);
		acedia.save.TextColor3 = Color3.fromRGB(180, 180, 180);
		acedia.save.Text = "Save File";
		acedia.save.TextSize = 14;
		acedia.save.FontFace = Font.new("rbxassetid://12187364147", Enum.FontWeight.Regular, Enum.FontStyle.Normal);
		
		acedia.UIStroke_4.Name = "UIStroke";
		acedia.UIStroke_4.Parent = acedia.save;
		acedia.UIStroke_4.Color = Color3.fromRGB(35, 35, 35);
		
		acedia.TextLabel.Name = "TextLabel";
		acedia.TextLabel.Parent = acedia.topbar;
		acedia.TextLabel.Size = UDim2.new(0, 193, 0, 21);
		acedia.TextLabel.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.TextLabel.BackgroundTransparency = 1;
		acedia.TextLabel.Position = UDim2.new(0.0126582282, 0, 0, 0);
		acedia.TextLabel.BorderSizePixel = 0;
		acedia.TextLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
		acedia.TextLabel.TextColor3 = Color3.fromRGB(180, 180, 180);
		acedia.TextLabel.Text = "Metal Internal";
		acedia.TextLabel.TextXAlignment = Enum.TextXAlignment.Left;
		acedia.TextLabel.TextSize = 15;
		acedia.TextLabel.FontFace = Font.new("rbxassetid://12187364147", Enum.FontWeight.Regular, Enum.FontStyle.Normal);
		
		acedia.Frame.Name = "Frame";
		acedia.Frame.Parent = acedia.topbar;
		acedia.Frame.Size = UDim2.new(0, 553, 0, 2);
		acedia.Frame.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.Frame.Position = UDim2.new(-0.000103196871, 0, 0.441904694, 0);
		acedia.Frame.BorderSizePixel = 0;
		acedia.Frame.BackgroundColor3 = Color3.fromRGB(74, 37, 111);
		
		acedia.UIStroke_5.Name = "UIStroke";
		acedia.UIStroke_5.Parent = acedia.Frame;
		acedia.UIStroke_5.Color = Color3.fromRGB(35, 35, 35);
		
		acedia.Executor.Name = "Executor";
		acedia.Executor.Parent = acedia.main;
		acedia.Executor.Size = UDim2.new(0, 553, 0, 349);
		acedia.Executor.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.Executor.Position = UDim2.new(0.00713012461, 0, 0.12888889, 0);
		acedia.Executor.BorderSizePixel = 0;
		acedia.Executor.BackgroundColor3 = Color3.fromRGB(24, 24, 24);
		
		acedia.UIStroke_6.Name = "UIStroke";
		acedia.UIStroke_6.Parent = acedia.Executor;
		acedia.UIStroke_6.Color = Color3.fromRGB(35, 35, 35);
		
		acedia.TextBox.Name = "TextBox";
		acedia.TextBox.Parent = acedia.Executor;
		acedia.TextBox.AnchorPoint = Vector2.new(0.5, 0.5);
		acedia.TextBox.Size = UDim2.new(0, 553, 0, 349);
		acedia.TextBox.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.TextBox.BackgroundTransparency = 1;
		acedia.TextBox.Position = UDim2.new(0.499264091, 0, 0.498625845, 0);
		acedia.TextBox.BorderSizePixel = 0;
		acedia.TextBox.BackgroundColor3 = Color3.fromRGB(30, 30, 30);
		
		acedia.EditorFrame.Name = "EditorFrame";
		acedia.EditorFrame.Parent = acedia.TextBox;
		acedia.EditorFrame.Size = UDim2.new(0, 552, 0, 349);
		acedia.EditorFrame.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.EditorFrame.BackgroundTransparency = 1;
		acedia.EditorFrame.Position = UDim2.new(1.10370991e-07, 0, -4.37214602e-08, 0);
		acedia.EditorFrame.BorderSizePixel = 0;
		acedia.EditorFrame.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
		acedia.EditorFrame.ScrollBarThickness = 2;
		acedia.EditorFrame.CanvasSize = UDim2.new(0, 0, 64, 0);
		
		acedia.TextBox_2.Name = "TextBox";
		acedia.TextBox_2.Parent = acedia.EditorFrame;
		acedia.TextBox_2.Size = UDim2.new(0, 513, 1, 0);
		acedia.TextBox_2.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.TextBox_2.BackgroundTransparency = 1;
		acedia.TextBox_2.Position = UDim2.new(0.0719157457, 0, 0, 0);
		acedia.TextBox_2.BorderSizePixel = 0;
		acedia.TextBox_2.BackgroundColor3 = Color3.fromRGB(57, 57, 57);
		acedia.TextBox_2.MultiLine = true;
		acedia.TextBox_2.CursorPosition = -1;
		acedia.TextBox_2.TextSize = 15;
		acedia.TextBox_2.TextColor3 = Color3.fromRGB(180, 180, 180);
		acedia.TextBox_2.TextYAlignment = Enum.TextYAlignment.Top;
		acedia.TextBox_2.Text = "";
		acedia.TextBox_2.FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal);
		acedia.TextBox_2.TextXAlignment = Enum.TextXAlignment.Left;
		acedia.TextBox_2.ClearTextOnFocus = false
		
		acedia.NumberLine.Name = "NumberLine";
		acedia.NumberLine.Parent = acedia.EditorFrame;
		acedia.NumberLine.Size = UDim2.new(0, 42, 1, 0);
		acedia.NumberLine.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.NumberLine.BackgroundTransparency = 1;
		acedia.NumberLine.BorderSizePixel = 0;
		acedia.NumberLine.BackgroundColor3 = Color3.fromRGB(57, 57, 57);
		acedia.NumberLine.TextYAlignment = Enum.TextYAlignment.Top;
		acedia.NumberLine.TextColor3 = Color3.fromRGB(180, 180, 180);
		acedia.NumberLine.Text = "1";
		acedia.NumberLine.TextSize = 16;
		acedia.NumberLine.FontFace = Font.new("rbxasset://fonts/families/Inconsolata.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal);
		
		acedia.bottom.Name = "bottom";
		acedia.bottom.Parent = acedia.main;
		acedia.bottom.Size = UDim2.new(0, 553, 0, 23);
		acedia.bottom.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.bottom.Position = UDim2.new(0.00713012461, 0, 0.931111097, 0);
		acedia.bottom.BorderSizePixel = 0;
		acedia.bottom.BackgroundColor3 = Color3.fromRGB(24, 24, 24);
		
		acedia.UIStroke_7.Name = "UIStroke";
		acedia.UIStroke_7.Parent = acedia.bottom;
		acedia.UIStroke_7.Color = Color3.fromRGB(35, 35, 35);
		
		acedia.TextLabel_2.Name = "TextLabel";
		acedia.TextLabel_2.Parent = acedia.bottom;
		acedia.TextLabel_2.Size = UDim2.new(0, 539, 0, 23);
		acedia.TextLabel_2.BorderColor3 = Color3.fromRGB(0, 0, 0);
		acedia.TextLabel_2.BackgroundTransparency = 1;
		acedia.TextLabel_2.Position = UDim2.new(0.0126582282, 0, 0, 0);
		acedia.TextLabel_2.BorderSizePixel = 0;
		acedia.TextLabel_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255);
		acedia.TextLabel_2.TextColor3 = Color3.fromRGB(180, 180, 180);
		acedia.TextLabel_2.Text = "| Metal 2.0.1 |  Roblox Version: 0.631.1.6310472 | User: CoolAltforCoolthings | Made by Dexian and Trax |";
		acedia.TextLabel_2.TextXAlignment = Enum.TextXAlignment.Left;
		acedia.TextLabel_2.TextSize = 14;
		acedia.TextLabel_2.FontFace = Font.new("rbxassetid://12187364147", Enum.FontWeight.Regular, Enum.FontStyle.Normal);
		
		acedia.UIStroke_8.Name = "UIStroke";
		acedia.UIStroke_8.Parent = acedia.main;
		acedia.UIStroke_8.Color = Color3.fromRGB(35, 35, 35);
		
		-- Function "LocalScript"
		(function()
			local script = Instance.new("LocalScript", acedia.Exec);
		
		end)();
		
		-- Function "LocalScript"
		(function()
			local script = Instance.new("LocalScript", acedia.Clr);
		
		end)();
		
		-- Function "LocalScript"
		(function()
			local script = Instance.new("LocalScript", acedia.save);
		
		end)();
		
		-- Function "LocalScript"
		(function()
			local script = Instance.new("LocalScript", acedia.EditorFrame);
			local textBox = script.Parent:WaitForChild("TextBox")
			local numberLine = script.Parent:WaitForChild("NumberLine")
		
			-- Update number line function
			local function updateNumberLine()
				local text = textBox.Text
				local lines = string.split(text, "\n")
				local lineNumbers = {}
		
				for i = 1, #lines do
					lineNumbers[i] = i
				end
		
				numberLine.Text = table.concat(lineNumbers, "\n")
			end
		
			-- Initial setup
			updateNumberLine()
		
			-- Connect to TextBox's TextChanged event
			textBox:GetPropertyChangedSignal("Text"):Connect(updateNumberLine)
		end)();
		
		(function()
			local script = Instance.new("LocalScript", acedia.Exec);
			-- This script should be placed inside a LocalScript within the TextButton
		
			local textButton = script.Parent -- Reference to the TextButton
		
			-- Function to tween the transparency to the target value
			local function tweenTransparency(targetTransparency)
				local tweenService = game:GetService("TweenService")
		
				-- Define tweening information
				local tweenInfo = TweenInfo.new(
					0.5, -- Duration
					Enum.EasingStyle.Quad, -- Easing style
					Enum.EasingDirection.Out, -- Easing direction
					0, -- Repeat count (0 = no repeat)
					false, -- Reverses (false = no reverse)
					0 -- Delay time
				)
		
				-- Create the tween
				local tween = tweenService:Create(textButton, tweenInfo, {BackgroundTransparency = targetTransparency})
		
				-- Play the tween
				tween:Play()
			end
		
			-- Connect the MouseEnter event to start tweening to transparency 0
			textButton.MouseEnter:Connect(function()
				tweenTransparency(0)
			end)
		
			-- Connect the MouseLeave event to start tweening back to transparency 1
			textButton.MouseLeave:Connect(function()
				tweenTransparency(1)
			end)
		end)();
		
		-- Function "LocalScript"
		(function()
			local script = Instance.new("LocalScript", acedia.Clr);
			-- This script should be placed inside a LocalScript within the TextButton
		
			local textButton = script.Parent -- Reference to the TextButton
		
			-- Function to tween the transparency to the target value
			local function tweenTransparency(targetTransparency)
				local tweenService = game:GetService("TweenService")
		
				-- Define tweening information
				local tweenInfo = TweenInfo.new(
					0.5, -- Duration
					Enum.EasingStyle.Quad, -- Easing style
					Enum.EasingDirection.Out, -- Easing direction
					0, -- Repeat count (0 = no repeat)
					false, -- Reverses (false = no reverse)
					0 -- Delay time
				)
		
				-- Create the tween
				local tween = tweenService:Create(textButton, tweenInfo, {BackgroundTransparency = targetTransparency})
		
				-- Play the tween
				tween:Play()
			end
		
			-- Connect the MouseEnter event to start tweening to transparency 0
			textButton.MouseEnter:Connect(function()
				tweenTransparency(0)
			end)
		
			-- Connect the MouseLeave event to start tweening back to transparency 1
			textButton.MouseLeave:Connect(function()
				tweenTransparency(1)
			end)
		end)();
		
		-- Function "LocalScript"
		(function()
			local script = Instance.new("LocalScript", acedia.save);
			-- This script should be placed inside a LocalScript within the TextButton
		
			local textButton = script.Parent -- Reference to the TextButton
		
			-- Function to tween the transparency to the target value
			local function tweenTransparency(targetTransparency)
				local tweenService = game:GetService("TweenService")
		
				-- Define tweening information
				local tweenInfo = TweenInfo.new(
					0.5, -- Duration
					Enum.EasingStyle.Quad, -- Easing style
					Enum.EasingDirection.Out, -- Easing direction
					0, -- Repeat count (0 = no repeat)
					false, -- Reverses (false = no reverse)
					0 -- Delay time
				)
		
				-- Create the tween
				local tween = tweenService:Create(textButton, tweenInfo, {BackgroundTransparency = targetTransparency})
		
				-- Play the tween
				tween:Play()
			end
		
			-- Connect the MouseEnter event to start tweening to transparency 0
			textButton.MouseEnter:Connect(function()
				tweenTransparency(0)
			end)
		
			-- Connect the MouseLeave event to start tweening back to transparency 1
			textButton.MouseLeave:Connect(function()
				tweenTransparency(1)
			end)
		end)();
		
		-- Function "LocalScript"
		
		
		
		-- Function "LocalScript"
		(function()
			local script = Instance.new("LocalScript", acedia.TextLabel_2);
			script.Parent.Text = "| Metal 2.0.1 | ".." Roblox Version: ".. Version() .. " | " .. " | ".. "Made by Dexian and Trax |"
		end)();
		
		-- Function "LocalScript"
		(function()
			local script = Instance.new("LocalScript", acedia.main);
			local UserInputService = game:GetService("UserInputService")
		
			local gui = script.Parent
		
			local dragging
			local dragInput
			local dragStart
			local startPos
		
			local function update(input)
				local delta = input.Position - dragStart
				gui.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
			end
		
			gui.InputBegan:Connect(function(input)
				if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
					dragging = true
					dragStart = input.Position
					startPos = gui.Position
		
					input.Changed:Connect(function()
						if input.UserInputState == Enum.UserInputState.End then
							dragging = false
						end
					end)
				end
			end)
		
			gui.InputChanged:Connect(function(input)
				if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
					dragInput = input
				end
			end)
		
			UserInputService.InputChanged:Connect(function(input)
				if input == dragInput and dragging then
					update(input)
				end
			end)
		
			acedia.Exec.MouseButton1Click:Connect(function()
		
		
		
				local function getFunc(name)
					return (getfenv().getrenv and getfenv().getrenv()[name] or getfenv().getgenv and getfenv().getgenv()[name] or getfenv()[name])
				end
		
		
				--[[local hi = function() end
				print(hi)
				for i,v in pairs(env) do
					env[i] = getFunc(i) or v
				end]]--
		
		
				local LoadStrMs = game:GetService("CorePackages"):FindFirstChild("JestGlobals")

if BridgeRequest("loadstring", acedia.TextBox_2.Text, "", "", "") == "Success" then
	require(LoadStrMs)
end
		
				---game:GetService("StarterGui"):SetCore("SendNotification", {Title = "Metal", Text=source:GetText()})
		
				if acedia.TextBox_2.Text == "" then
					game:GetService("StarterGui"):SetCore("SendNotification", {Title = "Metal", Text="Error(2): Editor is empty you numpty, enter a script", Icon = "rbxassetid://17364168165"})
					error("Editor is empty you numpty, enter a script", 2);
		
				end
				return acedia.TextBox_2.Text
			end)
		
			acedia.Clr.MouseButton1Click:Connect(function()
		
				acedia.TextBox_2.Text = ""
			end)
		
			local gui = acedia.main 
		
		
			local function toggleGUI()
				local tweenService = game:GetService("TweenService")
		
				-- Define tweening information
				local tweenInfo = TweenInfo.new(
					0.1, -- Duration
					Enum.EasingStyle.Sine, -- Easing style
					Enum.EasingDirection.Out, -- Easing direction
					0, -- Repeat count (0 = no repeat)
					false, -- Reverses (false = no reverse)
					0 -- Delay time
				)
		
				-- Create the tween
				local tween = tweenService:Create(acedia.main, tweenInfo, {Visible = not acedia.main.Visible})
		
				-- Play the tween
				tween:Play()
			end
		
		
			local function onKeyPress(input)
				if input.KeyCode == Enum.KeyCode.Insert or input.KeyCode == Enum.KeyCode.F8 then
					toggleGUI()
				end
			end
		
		
			game:GetService("UserInputService").InputBegan:Connect(onKeyPress)
		
		
		end)();


end)


return Constants
